### ISSUE TITLE
Incorrect unused warnings

### ISSUE THREAD

**Issue by backuitist** [scalameta/tutorial#17]
If I add the unused flag to the compiler (`-Ywarn-unused`) I get a lot of (seemingly) incorrect warnings (ex: `parameter value prefix in method apply is never used`). This is annoying when used in combination with `-Xfatal-warnings`.

I know this is the wrong place to report this, but I'm unsure whether it's a paradise bug or a scalameta bug. Probably the former?

**Comment by olafurpg** [comment]
Is are these errors reported against the expanded code from macro annotations? If so, can you please open a ticket in scalameta/paradise?

**Comment by backuitist** [comment]
No those are coming from the macro code:
```
MacroUtil.scala:6: parameter value defn in method helper is never used
```

**Comment by olafurpg** [comment]
Closing since scalameta/paradise is no longer under development. There is unfortunately no workaround for this issue.
