### ISSUE TITLE
Update the current state of scalameta website related repos.

### ISSUE THREAD

**Issue by ckipp01** [scalameta/tutorial#66]
I originally had opened #65 with hopes to get a couplet things updated such as the most recent version across the site so someone going through the docs would be using the latest.

However, I think it's worth a discussion before any changes are made.

I'll try to do my best to summarize why I think this is important below.

1. In it's current state, it's a bit confusing to have the scalameta repo, the tutorial site, and the scalameta.github.io repo. I'm assuming it's not confusing for those that were with the project from the start, but it confusing for newcomers for sure.
2. Related to the above point, I think having at least a bit more unification with correct labeling will help newcomers onboard to scalameta projects in numerous ways. For one, it will be easier to know how to contribute to docs, it will be easier to keep the docs up to date, and it will be clearer for newcomers going through the examples in the docs.
3. We seem to have a pattern of projects having a docs directory, and then using mdoc to create a docusaurus site by utilizing the gh-pages branch. This project breaks from that, which can be fine, but I don't see the need to have three repos, one for the source, and the other for the produced site source. Is it possible to unify the tutorial and scalameta.github.io repos?

I say all of this knowing that a ton of work has gone into this project, and I really want to be able to highlight that as much as possible, and also make it as smooth as possible for newer people to get involved. I'm more than happy to work on this, but would need a bit of info on how you'd want this layed out and moved around.

**Comment by olafurpg** [comment]
Reorganizing the scalameta.org docs is a good idea! Thank you for starting this discussion.

I agree the current situation is confusing. I believe we might be able to remove the dependency on scalafix and move the docs into the scalameta/scalameta repo. We recently upgraded the scalameta/scalameta sbt build to v1 from v0.13, which previously blocked the sbt-mdoc integration we're using in the tutorial repo.

By moving the docs to scalameta/scalameta, we can get rid of the docs-out hacks to pull in markdown files from the scalameta/scalameta repo. This would also help keep the website up to date with the latest scalameta versions. It's quite annoying to have to manually update the versions here. I prefer to push a tag and have the docs update automatically.

**Comment by olafurpg** [comment]
My biggest concern with moving the docs to scalameta/scalameta is that we introduce cyclic dependencies between repositories. The scalameta/mdoc repo depends on scalameta/scalameta. We strictly speaking don't introduce cyclic dependencies between projects, just cyclic dependencies between the sbt build.

**Comment by olafurpg** [comment]
We already have the same situation in MUnit, where the mdoc test suite uses MUnit and the MUnit documentation website uses mdoc.

**Comment by olafurpg** [comment]
I opened https://github.com/scalameta/scalameta/pull/1973 moving the docs to the main scalameta repo. Turns out the Scalafix dependency was not necessary, which simplified a lot of things.
