### ISSUE TITLE
Dep versioning issues

### ISSUE THREAD

**Issue by davesmith00000** [scalameta/tutorial#8]
Started following the tutorial, cloned this repo, ran `sbt clean update compile` and got:

```
build.sbt:5: error: value ScoverageKeys is not a member of object scoverage.ScoverageSbtPlugin
import scoverage.ScoverageSbtPlugin.ScoverageKeys._
                                    ^
build.sbt:48: error: value ScoverageKeys is not a member of object scoverage.ScoverageSbtPlugin
  ScoverageSbtPlugin.ScoverageKeys.coverageExcludedPackages :=
                     ^
sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
```

I've got around it by commenting out the coverage plugin and those two lines, but thought I'd mention it since people expecting this to work out of the box may be disappointed.

**Comment by olafurpg** [comment]
Thank you for reporting! This repo was originally fork of scalafix, and I never got through cleaning out all the unnecessary parts. I would be happy to merge what you did to get the repo working on your machine, even though it's only commenting out stuff :)

**Comment by olafurpg** [comment]
I've cleanup up this repo considerably in #13, removing most of the unnecessary stuff from the original scalafix fork. `sbt test` should pass and all version numbers should be up-to-date now, thank you for reporting!

**Comment by davesmith00000** [comment]
Great thanks, sorry I didn't get around to looking at it.
